# Form implementation generated from reading ui file 'delete.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 571)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_97 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_97.setObjectName("horizontalLayout_97")
        self.widget = QtWidgets.QWidget(parent=self.page_2)
        self.widget.setMaximumSize(QtCore.QSize(900, 400))
        self.widget.setStyleSheet("#widget {\n"
"background-color: rgb(228, 228, 228)\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Vopros = QtWidgets.QLineEdit(parent=self.widget)
        self.Vopros.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros.setFont(font)
        self.Vopros.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Vopros.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros.setObjectName("Vopros")
        self.horizontalLayout_8.addWidget(self.Vopros)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, -1, 228, -1)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.widget)
        self.dateEdit.setMaximumSize(QtCore.QSize(160, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("#dateEdit {\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"border-color:rgb(190, 190, 190) ;\n"
"background-color:rgb(243, 243, 243);\n"
"}\n"
"#dateEdit:hover {\n"
"background-color: rgb(243, 243, 243);\n"
"}\n"
"#dateEdit:pressed { \n"
"background-color:rgb(243, 243, 243);\n"
"}\n"
"\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_24.addWidget(self.dateEdit)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_24)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_97.addWidget(self.widget)
        self.verticalLayout_14.addLayout(self.horizontalLayout_97)
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_98 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_98.setObjectName("horizontalLayout_98")
        self.widget_3 = QtWidgets.QWidget(parent=self.page_4)
        self.widget_3.setMaximumSize(QtCore.QSize(900, 400))
        self.widget_3.setStyleSheet("#widget_3 {\n"
"background-color: rgb(228, 228, 228)\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_15.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Vopros_2 = QtWidgets.QLineEdit(parent=self.widget_3)
        self.Vopros_2.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros_2.setFont(font)
        self.Vopros_2.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Vopros_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros_2.setObjectName("Vopros_2")
        self.horizontalLayout_27.addWidget(self.Vopros_2)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_27)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.Kratki_otvet = QtWidgets.QLineEdit(parent=self.widget_3)
        self.Kratki_otvet.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Kratki_otvet.setFont(font)
        self.Kratki_otvet.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Kratki_otvet.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Kratki_otvet.setObjectName("Kratki_otvet")
        self.horizontalLayout_30.addWidget(self.Kratki_otvet)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_30)
        self.verticalLayout_15.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_98.addWidget(self.widget_3)
        self.verticalLayout_17.addLayout(self.horizontalLayout_98)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_99 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_99.setObjectName("horizontalLayout_99")
        self.widget_5 = QtWidgets.QWidget(parent=self.page_5)
        self.widget_5.setMaximumSize(QtCore.QSize(900, 400))
        self.widget_5.setStyleSheet("#widget_5 {\n"
"background-color: rgb(228, 228, 228)\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_18.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.Vopros_3 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.Vopros_3.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros_3.setFont(font)
        self.Vopros_3.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Vopros_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros_3.setObjectName("Vopros_3")
        self.horizontalLayout_35.addWidget(self.Vopros_3)
        self.horizontalLayout_34.addLayout(self.horizontalLayout_35)
        self.verticalLayout_18.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.Kratki_otvet_2 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.Kratki_otvet_2.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Kratki_otvet_2.setFont(font)
        self.Kratki_otvet_2.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Kratki_otvet_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Kratki_otvet_2.setObjectName("Kratki_otvet_2")
        self.horizontalLayout_38.addWidget(self.Kratki_otvet_2)
        self.horizontalLayout_37.addLayout(self.horizontalLayout_38)
        self.verticalLayout_18.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_99.addWidget(self.widget_5)
        self.verticalLayout_20.addLayout(self.horizontalLayout_99)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_100 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_100.setObjectName("horizontalLayout_100")
        self.widget_7 = QtWidgets.QWidget(parent=self.page_6)
        self.widget_7.setMaximumSize(QtCore.QSize(900, 400))
        self.widget_7.setStyleSheet("#widget_7 {\n"
"background-color: rgb(228, 228, 228)\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_21.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.Vopros_4 = QtWidgets.QLineEdit(parent=self.widget_7)
        self.Vopros_4.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros_4.setFont(font)
        self.Vopros_4.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Vopros_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros_4.setObjectName("Vopros_4")
        self.horizontalLayout_44.addWidget(self.Vopros_4)
        self.horizontalLayout_43.addLayout(self.horizontalLayout_44)
        self.verticalLayout_21.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.Kratki_otvet_3 = QtWidgets.QLineEdit(parent=self.widget_7)
        self.Kratki_otvet_3.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Kratki_otvet_3.setFont(font)
        self.Kratki_otvet_3.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Kratki_otvet_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Kratki_otvet_3.setObjectName("Kratki_otvet_3")
        self.horizontalLayout_47.addWidget(self.Kratki_otvet_3)
        self.horizontalLayout_46.addLayout(self.horizontalLayout_47)
        self.verticalLayout_21.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_100.addWidget(self.widget_7)
        self.verticalLayout_23.addLayout(self.horizontalLayout_100)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_101 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_101.setObjectName("horizontalLayout_101")
        self.widget_9 = QtWidgets.QWidget(parent=self.page_7)
        self.widget_9.setMaximumSize(QtCore.QSize(900, 400))
        self.widget_9.setStyleSheet("#widget_9 {\n"
"background-color: rgb(228, 228, 228)\n"
"}")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.Vopros_5 = QtWidgets.QLineEdit(parent=self.widget_9)
        self.Vopros_5.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros_5.setFont(font)
        self.Vopros_5.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Vopros_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros_5.setObjectName("Vopros_5")
        self.horizontalLayout_53.addWidget(self.Vopros_5)
        self.horizontalLayout_52.addLayout(self.horizontalLayout_53)
        self.verticalLayout_24.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.Kratki_otvet_4 = QtWidgets.QLineEdit(parent=self.widget_9)
        self.Kratki_otvet_4.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Kratki_otvet_4.setFont(font)
        self.Kratki_otvet_4.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Kratki_otvet_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Kratki_otvet_4.setObjectName("Kratki_otvet_4")
        self.horizontalLayout_56.addWidget(self.Kratki_otvet_4)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.horizontalLayout_55.addLayout(self.horizontalLayout_57)
        self.verticalLayout_24.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_101.addWidget(self.widget_9)
        self.verticalLayout_26.addLayout(self.horizontalLayout_101)
        self.stackedWidget_2.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.horizontalLayout_102 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_102.setObjectName("horizontalLayout_102")
        self.widget_11 = QtWidgets.QWidget(parent=self.page_8)
        self.widget_11.setMaximumSize(QtCore.QSize(900, 400))
        self.widget_11.setStyleSheet("#widget_11 {\n"
"background-color: rgb(228, 228, 228)\n"
"}")
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_27.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setContentsMargins(29, -1, 210, -1)
        self.horizontalLayout_64.setSpacing(0)
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.comboBox_6 = QtWidgets.QComboBox(parent=self.widget_11)
        self.comboBox_6.setMaximumSize(QtCore.QSize(60, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setStyleSheet("#comboBox_6 {\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"border-color:rgb(190, 190, 190) ;\n"
"background-color:rgb(243, 243, 243);\n"
"}\n"
"#comboBox_6:hover {\n"
"background-color: rgb(243, 243, 243);\n"
"}\n"
"#comboBox_6:pressed { \n"
"background-color:rgb(243, 243, 243);\n"
"}\n"
"")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.horizontalLayout_64.addWidget(self.comboBox_6)
        self.comboBox_7 = QtWidgets.QComboBox(parent=self.widget_11)
        self.comboBox_7.setMaximumSize(QtCore.QSize(60, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_7.setFont(font)
        self.comboBox_7.setStyleSheet("#comboBox_7 {\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"border-color:rgb(190, 190, 190) ;\n"
"background-color:rgb(243, 243, 243);\n"
"}\n"
"#comboBox_7:hover {\n"
"background-color: rgb(243, 243, 243);\n"
"}\n"
"#comboBox_7:pressed { \n"
"background-color:rgb(243, 243, 243);\n"
"}\n"
"")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.horizontalLayout_64.addWidget(self.comboBox_7)
        spacerItem = QtWidgets.QSpacerItem(60, 0, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem)
        self.horizontalLayout_63.addLayout(self.horizontalLayout_64)
        self.horizontalLayout_62.addLayout(self.horizontalLayout_63)
        self.horizontalLayout_61.addLayout(self.horizontalLayout_62)
        self.verticalLayout_27.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.horizontalLayout_93 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_93.setObjectName("horizontalLayout_93")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_70.setSpacing(6)
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_70.addItem(spacerItem1)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_71.setSpacing(6)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_71.addWidget(self.label_6)
        self.horizontalLayout_70.addLayout(self.horizontalLayout_71)
        self.Vopros_6 = QtWidgets.QLineEdit(parent=self.widget_11)
        self.Vopros_6.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros_6.setFont(font)
        self.Vopros_6.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Vopros_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros_6.setObjectName("Vopros_6")
        self.horizontalLayout_70.addWidget(self.Vopros_6)
        spacerItem2 = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_70.addItem(spacerItem2)
        self.verticalLayout_40.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setContentsMargins(-1, 30, 0, -1)
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem3)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_11)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_68.addWidget(self.label_5)
        self.horizontalLayout_67.addLayout(self.horizontalLayout_68)
        self.Kratki_otvet_5 = QtWidgets.QLineEdit(parent=self.widget_11)
        self.Kratki_otvet_5.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Kratki_otvet_5.setFont(font)
        self.Kratki_otvet_5.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Kratki_otvet_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Kratki_otvet_5.setObjectName("Kratki_otvet_5")
        self.horizontalLayout_67.addWidget(self.Kratki_otvet_5)
        spacerItem4 = QtWidgets.QSpacerItem(130, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_67.addItem(spacerItem4)
        self.verticalLayout_40.addLayout(self.horizontalLayout_67)
        self.horizontalLayout_93.addLayout(self.verticalLayout_40)
        self.horizontalLayout_66.addLayout(self.horizontalLayout_93)
        self.verticalLayout_27.addLayout(self.horizontalLayout_66)
        self.horizontalLayout_102.addWidget(self.widget_11)
        self.verticalLayout_30.addLayout(self.horizontalLayout_102)
        self.stackedWidget_2.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.horizontalLayout_95 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_95.setObjectName("horizontalLayout_95")
        self.widget_13 = QtWidgets.QWidget(parent=self.page_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_13.sizePolicy().hasHeightForWidth())
        self.widget_13.setSizePolicy(sizePolicy)
        self.widget_13.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_13.setMaximumSize(QtCore.QSize(900, 400))
        self.widget_13.setStyleSheet("#widget_13 {\n"
"background-color: rgb(228, 228, 228)\n"
"}")
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_31.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setContentsMargins(75, -1, -1, -1)
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.Vopros_7 = QtWidgets.QLineEdit(parent=self.widget_13)
        self.Vopros_7.setMaximumSize(QtCore.QSize(434, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros_7.setFont(font)
        self.Vopros_7.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Vopros_7.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Vopros_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros_7.setObjectName("Vopros_7")
        self.horizontalLayout_76.addWidget(self.Vopros_7)
        self.horizontalLayout_75.addLayout(self.horizontalLayout_76)
        self.horizontalLayout_74.addLayout(self.horizontalLayout_75)
        self.verticalLayout_31.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setSpacing(6)
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.horizontalLayout_94 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_94.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_94.setObjectName("horizontalLayout_94")
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_13)
        self.widget_17.setMaximumSize(QtCore.QSize(40, 40))
        self.widget_17.setObjectName("widget_17")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_17)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.widget_17)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.pushButton_18.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_94.addWidget(self.widget_17)
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.Kratki_otvet_6 = QtWidgets.QLineEdit(parent=self.widget_13)
        self.Kratki_otvet_6.setMaximumSize(QtCore.QSize(405, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Kratki_otvet_6.setFont(font)
        self.Kratki_otvet_6.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Kratki_otvet_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Kratki_otvet_6.setObjectName("Kratki_otvet_6")
        self.horizontalLayout_79.addWidget(self.Kratki_otvet_6)
        self.horizontalLayout_94.addLayout(self.horizontalLayout_79)
        self.horizontalLayout_78.addLayout(self.horizontalLayout_94)
        self.verticalLayout_31.addLayout(self.horizontalLayout_78)
        self.horizontalLayout_95.addWidget(self.widget_13)
        self.verticalLayout_33.addLayout(self.horizontalLayout_95)
        self.stackedWidget_2.addWidget(self.page_9)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_96 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_96.setObjectName("horizontalLayout_96")
        self.widget_15 = QtWidgets.QWidget(parent=self.page_3)
        self.widget_15.setMaximumSize(QtCore.QSize(900, 400))
        self.widget_15.setStyleSheet("#widget_15 {\n"
"background-color: rgb(228, 228, 228)\n"
"}")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_34.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.horizontalLayout_85 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_85.setObjectName("horizontalLayout_85")
        self.Vopros_8 = QtWidgets.QLineEdit(parent=self.widget_15)
        self.Vopros_8.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros_8.setFont(font)
        self.Vopros_8.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(228, 228, 228);")
        self.Vopros_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros_8.setObjectName("Vopros_8")
        self.horizontalLayout_85.addWidget(self.Vopros_8)
        self.horizontalLayout_84.addLayout(self.horizontalLayout_85)
        self.verticalLayout_34.addLayout(self.horizontalLayout_84)
        self.horizontalLayout_87 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_87.setObjectName("horizontalLayout_87")
        self.horizontalLayout_89 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_89.setContentsMargins(-1, -1, 298, -1)
        self.horizontalLayout_89.setObjectName("horizontalLayout_89")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.widget_15)
        self.timeEdit.setMaximumSize(QtCore.QSize(90, 45))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("#timeEdit {\n"
"border: 2px solid;\n"
"border-radius: 5px;\n"
"border-color:rgb(190, 190, 190) ;\n"
"background-color:rgb(243, 243, 243);\n"
"}\n"
"#timeEdit:hover {\n"
"background-color: rgb(243, 243, 243);\n"
"}\n"
"#timeEdit:pressed { \n"
"background-color:rgb(243, 243, 243);\n"
"}\n"
"")
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_89.addWidget(self.timeEdit)
        self.horizontalLayout_87.addLayout(self.horizontalLayout_89)
        self.verticalLayout_34.addLayout(self.horizontalLayout_87)
        self.horizontalLayout_96.addWidget(self.widget_15)
        self.verticalLayout_36.addLayout(self.horizontalLayout_96)
        self.stackedWidget_2.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Button_Trash = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_Trash.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Trash.setFont(font)
        self.Button_Trash.setStyleSheet("#Button_Trash {\n"
"border-top: 2px solid;\n"
"border-top-color: rgb(255, 76, 0);\n"
"border-bottom: 2px solid;\n"
"border-bottom-color: rgb(255, 76, 0);\n"
"}\n"
"#Button_Trash:hover {\n"
"\n"
"}\n"
"#Button_Trash:pressed { \n"
"\n"
"}")
        self.Button_Trash.setObjectName("Button_Trash")
        self.horizontalLayout_4.addWidget(self.Button_Trash)
        self.Button_Save = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_Save.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Save.setFont(font)
        self.Button_Save.setStyleSheet("#Button_Save {\n"
"border-top: 2px solid;\n"
"border-top-color: rgb(255, 76, 0);\n"
"border-bottom: 2px solid;\n"
"border-bottom-color: rgb(255, 76, 0);\n"
"}\n"
"#Button_Save:hover {\n"
"\n"
"}\n"
"#Button_Save:pressed { \n"
"\n"
"}")
        self.Button_Save.setObjectName("Button_Save")
        self.horizontalLayout_4.addWidget(self.Button_Save)
        self.Button_Back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Button_Back.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Back.setFont(font)
        self.Button_Back.setStyleSheet("#Button_Back {\n"
"border-top: 2px solid;\n"
"border-top-color: rgb(255, 76, 0);\n"
"border-bottom: 2px solid;\n"
"border-bottom-color: rgb(255, 76, 0);\n"
"}\n"
"#Button_Back:hover {\n"
"\n"
"}\n"
"#Button_Back:pressed { \n"
"\n"
"}")
        self.Button_Back.setObjectName("Button_Back")
        self.horizontalLayout_4.addWidget(self.Button_Back)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_2.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Vopros.setPlaceholderText(_translate("MainWindow", "Вопрос"))
        self.Vopros_2.setPlaceholderText(_translate("MainWindow", "Вопрос"))
        self.Kratki_otvet.setPlaceholderText(_translate("MainWindow", "Краткий ответ"))
        self.Vopros_3.setPlaceholderText(_translate("MainWindow", "Вопрос"))
        self.Kratki_otvet_2.setPlaceholderText(_translate("MainWindow", "1 Вариант"))
        self.Vopros_4.setPlaceholderText(_translate("MainWindow", "Вопрос"))
        self.Kratki_otvet_3.setPlaceholderText(_translate("MainWindow", "1 Вариант"))
        self.Vopros_5.setPlaceholderText(_translate("MainWindow", "Вопрос"))
        self.Kratki_otvet_4.setPlaceholderText(_translate("MainWindow", "Развернутый ответ"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "3"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "4"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "5"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "6"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "7"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "8"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "9"))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "10"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.Vopros_6.setPlaceholderText(_translate("MainWindow", "Подпись (необязательно)"))
        self.label_5.setText(_translate("MainWindow", "2"))
        self.Kratki_otvet_5.setPlaceholderText(_translate("MainWindow", "Подпись (необязательно)"))
        self.Vopros_7.setPlaceholderText(_translate("MainWindow", "Вопрос"))
        self.Kratki_otvet_6.setPlaceholderText(_translate("MainWindow", "1 Вариант"))
        self.Vopros_8.setPlaceholderText(_translate("MainWindow", "Вопрос"))
        self.Button_Trash.setText(_translate("MainWindow", "Удалить"))
        self.Button_Save.setText(_translate("MainWindow", "Сохранить"))
        self.Button_Back.setText(_translate("MainWindow", "Назад"))
