# Form implementation generated from reading ui file 'Forma.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 557)
        MainWindow.setMaximumSize(QtCore.QSize(790, 443434))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 791, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(777, 112))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.505682, y1:0, x2:0.501, y2:0.511, stop:0 rgba(19, 19, 19, 255), stop:0.0227273 rgba(89, 67, 42, 239), stop:1 rgba(249, 179, 96, 200));\n"
"border-top-left-radius: 55px;\n"
"border-top-right-radius: 55px;\n"
"border-bottom-left-radius: 22px;\n"
"border-bottom-right-radius: 22px;\n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_14.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(120, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3 {\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton_3:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_3:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4 {\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton_4:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_4:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame.setMaximumSize(QtCore.QSize(729, 284))
        self.frame.setStyleSheet("#frame {\n"
"border: 4px solid;\n"
"border-radius: 10px;\n"
"border-color: #8E8080;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 731, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.textEdit = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget_2)
        self.textEdit.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("#textEdit {\n"
"background-color: rgb(181, 173, 173);\n"
"}\n"
"#textEdit:Focus {\n"
"background-color: rgb(219, 219, 219);\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_8.addWidget(self.textEdit)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_5.setMaximumSize(QtCore.QSize(141, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5 {\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton_5:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_5:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget_2)
        self.textEdit_2.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("#textEdit_2 {\n"
"background-color: rgb(181, 173, 173);\n"
"}\n"
"#textEdit_2:Focus {\n"
"background-color: rgb(219, 219, 219);\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_12.addWidget(self.textEdit_2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_6.setMaximumSize(QtCore.QSize(100, 48))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6 {\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton_6:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_6:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_11.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_7.setMaximumSize(QtCore.QSize(37, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("#pushButton_7 {\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton_7:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_7:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_11.addWidget(self.pushButton_7)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_11.setMaximumSize(QtCore.QSize(43, 41))
        self.pushButton_11.setStyleSheet("#pushButton_11 {\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4;\n"
"image: url(:/Copycopycopy/Copycopycopy.png);\n"
"}\n"
"#pushButton_11:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_11:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_13.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_10.setMaximumSize(QtCore.QSize(43, 41))
        self.pushButton_10.setStyleSheet("#pushButton_10 {\n"
"image: url(:/Trashcan/trashcan.png);\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton_10:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_10:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_13.addWidget(self.pushButton_10)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(400, 34))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButton_8.setMaximumSize(QtCore.QSize(43, 41))
        self.pushButton_8.setStyleSheet("#pushButton_8 {\n"
"border: 3px solid;\n"
"image: url(:/Galka_pustaya/galka.png);\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton_8:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_8:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_13.addWidget(self.pushButton_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton {\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2 {\n"
"border: 3px solid;\n"
"border-radius: 9px;\n"
"border-color: #7A6D6D;\n"
"background-color: #BBB4B4\n"
"}\n"
"#pushButton_2:hover {\n"
"background-color: rgb(219, 219, 219);\n"
"}\n"
"#pushButton_2:pressed { \n"
"background-color: #BBB4B4;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ДОБАВОЧНОЕ ПОЛЕ"))
        self.label_2.setText(_translate("MainWindow", "ДОБАВИТЬ ДОКУМЕНТ"))
        self.pushButton_3.setText(_translate("MainWindow", "ДОК."))
        self.pushButton_4.setText(_translate("MainWindow", "+ ФОРМА"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "ВОПРОС"))
        self.pushButton_5.setText(_translate("MainWindow", "ОДИН ИЗ\n"
"СПИСКА"))
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", "КРАТКИЙ ОТВЕТ"))
        self.pushButton_6.setText(_translate("MainWindow", "ТЭГ"))
        self.pushButton_7.setText(_translate("MainWindow", "?"))
        self.label_3.setText(_translate("MainWindow", "ОБЯЗАТЕЛЬНЫЙ ВОПРОС"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_2.setText(_translate("MainWindow", "Назад"))
