# Form implementation generated from reading ui file 'Main_Form.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Main_page = QtWidgets.QWidget()
        self.Main_page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Main_page.setObjectName("Main_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Main_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Glavnaya = QtWidgets.QLabel(parent=self.Main_page)
        self.Glavnaya.setMaximumSize(QtCore.QSize(760, 142))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.Glavnaya.setFont(font)
        self.Glavnaya.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.Glavnaya.setStyleSheet("")
        self.Glavnaya.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Glavnaya.setObjectName("Glavnaya")
        self.horizontalLayout_5.addWidget(self.Glavnaya)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_Zapolnit = QtWidgets.QPushButton(parent=self.Main_page)
        self.Button_Zapolnit.setMaximumSize(QtCore.QSize(270, 180))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Button_Zapolnit.setFont(font)
        self.Button_Zapolnit.setStyleSheet("#Button_Zapolnit{\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Zapolnit:hover {\n"
"\n"
"}\n"
"#Button_Zapolnit:pressed {\n"
"\n"
"}")
        self.Button_Zapolnit.setObjectName("Button_Zapolnit")
        self.horizontalLayout.addWidget(self.Button_Zapolnit)
        self.Button_Spisok = QtWidgets.QPushButton(parent=self.Main_page)
        self.Button_Spisok.setMaximumSize(QtCore.QSize(270, 180))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Button_Spisok.setFont(font)
        self.Button_Spisok.setStyleSheet("#Button_Spisok{\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Spisok:hover {\n"
"\n"
"}\n"
"#Button_Spisok:pressed {\n"
"\n"
"}")
        self.Button_Spisok.setObjectName("Button_Spisok")
        self.horizontalLayout.addWidget(self.Button_Spisok)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.Main_page)
        self.Add_page = QtWidgets.QWidget()
        self.Add_page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Add_page.setObjectName("Add_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Add_page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.Dobavochnoe_pole = QtWidgets.QLabel(parent=self.Add_page)
        self.Dobavochnoe_pole.setMaximumSize(QtCore.QSize(777, 112))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.Dobavochnoe_pole.setFont(font)
        self.Dobavochnoe_pole.setStyleSheet("")
        self.Dobavochnoe_pole.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Dobavochnoe_pole.setObjectName("Dobavochnoe_pole")
        self.horizontalLayout_14.addWidget(self.Dobavochnoe_pole)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Dobavit_dokument_label = QtWidgets.QLabel(parent=self.Add_page)
        self.Dobavit_dokument_label.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Dobavit_dokument_label.setFont(font)
        self.Dobavit_dokument_label.setStyleSheet("border-bottom: 2px solid black;\n"
"")
        self.Dobavit_dokument_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Dobavit_dokument_label.setObjectName("Dobavit_dokument_label")
        self.horizontalLayout_2.addWidget(self.Dobavit_dokument_label)
        self.Button_Dok = QtWidgets.QPushButton(parent=self.Add_page)
        self.Button_Dok.setMaximumSize(QtCore.QSize(180, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Dok.setFont(font)
        self.Button_Dok.setStyleSheet("#Button_Dok {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Dok:hover {\n"
"}\n"
"#Button_Dok:pressed { \n"
"}")
        self.Button_Dok.setObjectName("Button_Dok")
        self.horizontalLayout_2.addWidget(self.Button_Dok)
        self.Button_Forma_plus = QtWidgets.QPushButton(parent=self.Add_page)
        self.Button_Forma_plus.setMaximumSize(QtCore.QSize(130, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Forma_plus.setFont(font)
        self.Button_Forma_plus.setStyleSheet("#Button_Forma_plus {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Forma_plus:hover {\n"
"\n"
"}\n"
"#Button_Forma_plus:pressed { \n"
"\n"
"}")
        self.Button_Forma_plus.setObjectName("Button_Forma_plus")
        self.horizontalLayout_2.addWidget(self.Button_Forma_plus)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.Add_page)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 417, 198))
        self.scrollAreaWidgetContents_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_3)
        self.widget.setStyleSheet("#widget {\n"
"background-color: rgb(194, 194, 194)\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Vopros = QtWidgets.QLineEdit(parent=self.widget)
        self.Vopros.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Vopros.setFont(font)
        self.Vopros.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(194, 194, 194);")
        self.Vopros.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Vopros.setObjectName("Vopros")
        self.horizontalLayout_8.addWidget(self.Vopros)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Odin_iz_spiska = QtWidgets.QPushButton(parent=self.widget)
        self.Odin_iz_spiska.setMaximumSize(QtCore.QSize(141, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Odin_iz_spiska.setFont(font)
        self.Odin_iz_spiska.setStyleSheet("#Odin_iz_spiska {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Odin_iz_spiska:hover {\n"
"\n"
"}\n"
"#Odin_iz_spiska:pressed { \n"
"\n"
"}")
        self.Odin_iz_spiska.setObjectName("Odin_iz_spiska")
        self.horizontalLayout_9.addWidget(self.Odin_iz_spiska)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Kratki_otvet = QtWidgets.QLineEdit(parent=self.widget)
        self.Kratki_otvet.setMaximumSize(QtCore.QSize(425, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Kratki_otvet.setFont(font)
        self.Kratki_otvet.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(194, 194, 194);")
        self.Kratki_otvet.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Kratki_otvet.setObjectName("Kratki_otvet")
        self.horizontalLayout_12.addWidget(self.Kratki_otvet)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Tag = QtWidgets.QLineEdit(parent=self.widget)
        self.Tag.setMaximumSize(QtCore.QSize(100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Tag.setFont(font)
        self.Tag.setStyleSheet("border-top: 0px solid;\n"
"border-bottom: 2px solid;\n"
"background-color: rgb(194, 194, 194);")
        self.Tag.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.Tag.setObjectName("Tag")
        self.horizontalLayout_11.addWidget(self.Tag)
        self.Button_Question = QtWidgets.QPushButton(parent=self.widget)
        self.Button_Question.setMaximumSize(QtCore.QSize(37, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Question.setFont(font)
        self.Button_Question.setStyleSheet("#Button_Question {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Question:hover {\n"
"\n"
"}\n"
"#Button_Question:pressed { \n"
"\n"
"}")
        self.Button_Question.setObjectName("Button_Question")
        self.horizontalLayout_11.addWidget(self.Button_Question)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Button_Copy = QtWidgets.QPushButton(parent=self.widget)
        self.Button_Copy.setMaximumSize(QtCore.QSize(43, 41))
        self.Button_Copy.setStyleSheet("#Button_Copy {\n"
"image: url(:/Copycopycopy/Copycopycopy.png);\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Copy:hover {\n"
"\n"
"}\n"
"#Button_Copy:pressed { \n"
"\n"
"}")
        self.Button_Copy.setText("")
        self.Button_Copy.setObjectName("Button_Copy")
        self.horizontalLayout_13.addWidget(self.Button_Copy)
        self.Obyazatelny_vopros = QtWidgets.QLabel(parent=self.widget)
        self.Obyazatelny_vopros.setMaximumSize(QtCore.QSize(400, 34))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Obyazatelny_vopros.setFont(font)
        self.Obyazatelny_vopros.setObjectName("Obyazatelny_vopros")
        self.horizontalLayout_13.addWidget(self.Obyazatelny_vopros)
        self.Button_Galka = QtWidgets.QPushButton(parent=self.widget)
        self.Button_Galka.setMaximumSize(QtCore.QSize(43, 41))
        self.Button_Galka.setStyleSheet("#Button_Galka {\n"
"image: url(:/Galka/galka.png);\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Galka:hover {\n"
"\n"
"}\n"
"#Button_Galka:pressed { \n"
"\n"
"}")
        self.Button_Galka.setText("")
        self.Button_Galka.setObjectName("Button_Galka")
        self.horizontalLayout_13.addWidget(self.Button_Galka)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.verticalLayout_7.addWidget(self.widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Button_Trash = QtWidgets.QPushButton(parent=self.Add_page)
        self.Button_Trash.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Trash.setFont(font)
        self.Button_Trash.setStyleSheet("#Button_Trash {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Trash:hover {\n"
"\n"
"}\n"
"#Button_Trash:pressed { \n"
"\n"
"}")
        self.Button_Trash.setObjectName("Button_Trash")
        self.horizontalLayout_4.addWidget(self.Button_Trash)
        self.Button_Save = QtWidgets.QPushButton(parent=self.Add_page)
        self.Button_Save.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Save.setFont(font)
        self.Button_Save.setStyleSheet("#Button_Save {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Save:hover {\n"
"\n"
"}\n"
"#Button_Save:pressed { \n"
"\n"
"}")
        self.Button_Save.setObjectName("Button_Save")
        self.horizontalLayout_4.addWidget(self.Button_Save)
        self.Button_Back = QtWidgets.QPushButton(parent=self.Add_page)
        self.Button_Back.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Back.setFont(font)
        self.Button_Back.setStyleSheet("#Button_Back {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Back:hover {\n"
"\n"
"}\n"
"#Button_Back:pressed { \n"
"\n"
"}")
        self.Button_Back.setObjectName("Button_Back")
        self.horizontalLayout_4.addWidget(self.Button_Back)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addLayout(self.verticalLayout_2)
        self.stackedWidget.addWidget(self.Add_page)
        self.Fill_page = QtWidgets.QWidget()
        self.Fill_page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Fill_page.setObjectName("Fill_page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Fill_page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(parent=self.Fill_page)
        self.label.setMaximumSize(QtCore.QSize(777, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_2 = QtWidgets.QLabel(parent=self.Fill_page)
        self.label_2.setMaximumSize(QtCore.QSize(600, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#label_2 {\n"
"border-bottom: 2px solid;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_20.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.Poisk = QtWidgets.QTextEdit(parent=self.Fill_page)
        self.Poisk.setMaximumSize(QtCore.QSize(430, 64))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Poisk.setFont(font)
        self.Poisk.setStyleSheet("#Poisk {\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Poisk:Focus {\n"
"\n"
"}")
        self.Poisk.setObjectName("Poisk")
        self.horizontalLayout_18.addWidget(self.Poisk)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.Fill_page)
        self.textEdit_2.setMaximumSize(QtCore.QSize(430, 64))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_19.addWidget(self.textEdit_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Button_Save_Fill = QtWidgets.QPushButton(parent=self.Fill_page)
        self.Button_Save_Fill.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Save_Fill.setFont(font)
        self.Button_Save_Fill.setStyleSheet("#Button_Save_Fill {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Save_Fill:hover {\n"
"\n"
"}\n"
"#Button_Save_Fill:pressed { \n"
"\n"
"}")
        self.Button_Save_Fill.setObjectName("Button_Save_Fill")
        self.horizontalLayout_16.addWidget(self.Button_Save_Fill)
        self.Button_Back_Fill = QtWidgets.QPushButton(parent=self.Fill_page)
        self.Button_Back_Fill.setMaximumSize(QtCore.QSize(157, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Button_Back_Fill.setFont(font)
        self.Button_Back_Fill.setStyleSheet("#Button_Back_Fill {\n"
"border-top: 2px solid;\n"
"border-bottom: 2px solid;\n"
"}\n"
"#Button_Back_Fill:hover {\n"
"\n"
"}\n"
"#Button_Back_Fill:pressed { \n"
"\n"
"}")
        self.Button_Back_Fill.setObjectName("Button_Back_Fill")
        self.horizontalLayout_16.addWidget(self.Button_Back_Fill)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.Fill_page)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Glavnaya.setText(_translate("MainWindow", "ГЛАВНАЯ"))
        self.Button_Zapolnit.setText(_translate("MainWindow", " ЗАПОЛНИТЬ\n"
"ДОКУМЕНТ"))
        self.Button_Spisok.setText(_translate("MainWindow", "СПИСОК\n"
"ФОРМ"))
        self.Dobavochnoe_pole.setText(_translate("MainWindow", "РЕДАКТОР ФОРМ"))
        self.Dobavit_dokument_label.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.Button_Dok.setText(_translate("MainWindow", "ДОКУМЕНТ"))
        self.Button_Forma_plus.setText(_translate("MainWindow", "ФОРМА"))
        self.Vopros.setPlaceholderText(_translate("MainWindow", "Вопрос"))
        self.Odin_iz_spiska.setText(_translate("MainWindow", "ОДИН ИЗ\n"
"СПИСКА"))
        self.Kratki_otvet.setPlaceholderText(_translate("MainWindow", "Краткий ответ"))
        self.Tag.setPlaceholderText(_translate("MainWindow", "Тэг"))
        self.Button_Question.setText(_translate("MainWindow", "?"))
        self.Obyazatelny_vopros.setText(_translate("MainWindow", "ОБЯЗАТЕЛЬНЫЙ ВОПРОС"))
        self.Button_Trash.setText(_translate("MainWindow", "Удалить"))
        self.Button_Save.setText(_translate("MainWindow", "Сохранить"))
        self.Button_Back.setText(_translate("MainWindow", "Назад"))
        self.label.setText(_translate("MainWindow", "ЗАПОЛНИТЬ ДОКУМЕНТ"))
        self.label_2.setText(_translate("MainWindow", "Название формы / название документа"))
        self.Button_Save_Fill.setText(_translate("MainWindow", "СОХРАНИТЬ"))
        self.Button_Back_Fill.setText(_translate("MainWindow", "НАЗАД"))
